import sqlite3
import pandas as pd
from pathlib import Path

DB_PATH = "ufo.db"
SCHEMA_PATH = "schema.sql"
DATA_URL = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2019/2019-06-25/ufo_sightings.csv"

INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_ufo_state ON ufo_sightings(state);
CREATE INDEX IF NOT EXISTS idx_ufo_country ON ufo_sightings(country);
CREATE INDEX IF NOT EXISTS idx_ufo_shape ON ufo_sightings(ufo_shape);
CREATE INDEX IF NOT EXISTS idx_ufo_date_time ON ufo_sightings(date_time);
"""

EXPECTED_COLS = {
    "date_time", "city_area", "state", "country", "ufo_shape",
    "encounter_length", "described_encounter_length", "description",
    "date_documented", "latitude", "longitude"
}

def main():
    print("Downloading UFO data...")
    try:
        df = pd.read_csv(DATA_URL)
    except Exception as e:
        raise RuntimeError(f"Failed to download dataset from {DATA_URL}: {e}")

    missing = EXPECTED_COLS - set(df.columns)
    if missing:
        raise ValueError(f"Dataset missing expected columns: {sorted(missing)}")

    # Normalize date_time to ISO 8601 so SQLite strftime() works reliably
    dt = pd.to_datetime(df["date_time"], errors="coerce")
    df["date_time"] = dt.dt.strftime("%Y-%m-%d %H:%M:%S")
    # Keep rows even if date_time is null; analysis filters those as needed

    # Ensure only schema columns are inserted (id is generated by SQLite)
    df = df[list(EXPECTED_COLS)]

    schema_sql = Path(SCHEMA_PATH).read_text(encoding="utf-8")

    print("Building SQLite database...")
    conn = sqlite3.connect(DB_PATH)
    try:
        with conn:  # transaction boundary
            conn.executescript(schema_sql)
            df.to_sql("ufo_sightings", conn, if_exists="append", index=False)
            conn.executescript(INDEX_SQL)
    finally:
        conn.close()

    print(f"Ingestion complete. Database saved as {DB_PATH}")

if __name__ == "__main__":
    main()